### ISSUE TITLE
issue installing module on python 3.5 (`distribute_setup.py` failing painfully)

### ISSUE THREAD

**Issue by guyzmo** [ned14/automodinit#5]
When installing on python 3.5, the module fails miserably, with the following error:

```
TypeError: chown() missing 1 required positional argument: 'numeric_owner'
```

I first looked at the sources, and did not find the culprit. It's only when I actually downloaded the zip file, that I discovered it was actually featuring an extra module: `distribute_setup.py`. Within it, it's using the tarfile module, which has had an API change.

It looks like it's because the `chown()` method of the `tarfile` module has changed at some point, even though it's not been documented (that method is not even in the module's documentation):

```
https://hg.python.org/cpython/file/3.5/Lib/tarfile.py#l2211
```

though, I really wonder that in 2016, the `distribute_setup.py` is really necessary to keep. All older versions of python are not supported, and python2.7 and all python3 support `distribute` per default. Could you remove that and refresh the pypi uploaded module?

**Comment by cypreess** [comment]
+1

**Comment by toyg** [comment]
On 3.4 I get:

```
    error: invalid command 'bdist_egg'
    /tmp/tmpviaertzvpycharm-packaging/automodinit/distribute-0.6.19-py3.4.egg
    Traceback (most recent call last):
      File "/tmp/tmpviaertzvpycharm-packaging/automodinit/distribute_setup.py", line 143, in use_setuptools
        raise ImportError
    ImportError
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/tmpviaertzvpycharm-packaging/automodinit/setup.py", line 9, in <module>
        use_setuptools()
      File "/tmp/tmpviaertzvpycharm-packaging/automodinit/distribute_setup.py", line 145, in use_setuptools
        return _do_download(version, download_base, to_dir, download_delay)
      File "/tmp/tmpviaertzvpycharm-packaging/automodinit/distribute_setup.py", line 125, in _do_download
        _build_egg(egg, tarball, to_dir)
      File "/tmp/tmpviaertzvpycharm-packaging/automodinit/distribute_setup.py", line 116, in _build_egg
        raise IOError('Could not build the egg.')
    OSError: Could not build the egg.
 ```

It really could do with a refreshed package.

**Comment by ned14** [comment]
Fixed, thanks for the report.
